name: Build and Upload Binary

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'

      - name: Build binary
        run: make build

      - name: Upload binary
        env:
          GITEA_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          mkdir -p release
          mv ./path/to/your/binary ./release/binary-$VERSION
          curl -X POST "https://git.scottyc.dev/api/v1/repos/scottyc/weather/releases" \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITEA_TOKEN" \
          -d '{
                "tag_name": "'$VERSION'",
                "target_commitish": "main",
                "name": "Release '$VERSION'",
                "body": "Description for release '$VERSION'",
                "draft": false,
                "prerelease": false
              }'
          curl -X POST "https://git.scottyc.ev/api/v1/repos/scottyc/weather/releases/$VERSION/assets" \
          -H "Authorization: token $GITEA_TOKEN" \
          -F "name=binary-$VERSION" \
          -F "file=@./release/binary-$VERSION"
name: Build and Upload Binary